name: tests

# TODO: add coverage + coveralls?

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  tests-on-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run tox -r
        env:
          FORCE_COLOR: 1
